version: "3.9"
services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    networks:
      - click-battle-network

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    networks:
      - click-battle-network
    depends_on:
      - backend

networks:
  click-battle-network:
    driver: bridge
